name: fm_template
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
  # flutter: 3.32.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.1
  pretty_dio_logger: ^1.4.0
  equatable: ^2.0.7
  connectivity_plus: ^6.1.4
  auto_route: ^10.1.0+1
  freezed_annotation: ^3.0.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  logging: ^1.3.0

  # local packages
  storage:
    path: ../packages/storage
  rest_client:
    path: ../packages/rest_client
  app_ui:
    path: ../packages/app_ui

  # test
  mocktail: ^1.0.4
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_lints: ^6.0.0
  injectable_generator: ^2.7.0
  build_runner: ^2.5.4
  auto_route_generator: ^10.1.0
  test: ^1.25.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5


flutter:
  uses-material-design: true
